export const APPOINTMENT_LABELS = [
  {
    language: 'polish',
    header: 'Umów wizytę',
    appointmentType: 'Typ wizyty',
    appointmentTypeOptions: ['Badanie wzroku', 'Naprawa', 'Dobór oprawek'],
    appointmentDate: 'Data',
    appointmentHour: 'Godzina',
    appointmentName: 'Imię',
    appointmentSurname: 'Nazwisko',
    appointmentPhone: 'Numer Telefonu',
    button: 'Potwierdź',
  },
  {
    language: 'english',
    header: 'Make an appointment',
    appointmentType: 'Type of appointment',
    appointmentTypeOptions: ['Eye test', 'Repair', 'Rims selection'],
    appointmentDate: 'Date',
    appointmentHour: 'Hour',
    appointmentName: 'Name',
    appointmentSurname: 'Surname',
    appointmentPhone: 'Phone number',
    button: 'Confirm',
  },
  {
    language: 'french',
    header: 'Prendre rendez-vous',
    appointmentType: 'Type de rendez-vous',
    appointmentTypeOptions: [
      'Examen des yeux',
      'Réparation',
      'Sélection de montures de lunettes',
    ],
    appointmentDate: 'Date',
    appointmentHour: 'Heure',
    appointmentName: 'Nom',
    appointmentSurname: 'Nom de famille',
    appointmentPhone: 'Numéro de téléphone',
    button: 'Confirmez',
  },
];
