import { APPOINTMENT_TYPE_LABELS } from './appointmentType.labels';

export const APPOINTMENT_LABELS = [
  {
    language: 'polish',
    header: 'Umów wizytę',
    appointmentType: 'Typ wizyty',
    appointmentTypeOptions: APPOINTMENT_TYPE_LABELS[0].type,
    appointmentDate: 'Data',
    appointmentHour: 'Godzina',
    appointmentName: 'Imię',
    appointmentSurname: 'Nazwisko',
    appointmentPhone: 'Numer Telefonu',
    button: 'Potwierdź',
  },
  {
    language: 'english',
    header: 'Make an appointment',
    appointmentType: 'Type of appointment',
    appointmentTypeOptions: APPOINTMENT_TYPE_LABELS[1].type,
    appointmentDate: 'Date',
    appointmentHour: 'Hour',
    appointmentName: 'Name',
    appointmentSurname: 'Surname',
    appointmentPhone: 'Phone number',
    button: 'Confirm',
  },
  {
    language: 'french',
    header: 'Prendre rendez-vous',
    appointmentType: 'Type de rendez-vous',
    appointmentTypeOptions: APPOINTMENT_TYPE_LABELS[2].type,
    appointmentDate: 'Date',
    appointmentHour: 'Heure',
    appointmentName: 'Nom',
    appointmentSurname: 'Nom de famille',
    appointmentPhone: 'Numéro de téléphone',
    button: 'Confirmez',
  },
];
