import { REPAIR_STATUS_LABELS } from './repairStatus.labels';

export const DOCTOR_LABELS = [
  {
    language: 'polish',
    header: 'Strefa lekarza',
    loginHeader: 'Zaloguj się',
    loginId: 'Id lekarza',
    dateHeader: 'Zarządzaj datami',
    dateLabel: 'Wybierz datę',
    date: 'Data',
    cancelButton: 'Odwołaj',
    repairHeader: 'Zarządzaj zgłoszeniami',
    repairId: 'Numer zgłoszenia',
    repairStatus: 'Status zgłoszenia',
    repairStatusOptions: REPAIR_STATUS_LABELS[0].status,
    repairButton: 'Zmień status',
  },
  {
    language: 'english',
    header: 'Doctor zone',
    loginHeader: 'Log in',
    loginId: 'Doctor id',
    dateHeader: 'Manage the dates',
    dateLabel: 'Choose date',
    date: 'Date',
    cancelButton: 'Cancel',
    repairHeader: 'Manage the reports',
    repairId: 'Report number',
    repairStatus: 'Report status',
    repairStatusOptions: REPAIR_STATUS_LABELS[1].status,
    repairButton: 'Change status',
  },
  {
    language: 'french',
    header: 'Zone médecin',
    loginHeader: 'Se connecter',
    loginId: 'ID du médecin',
    dateHeader: 'Gérer les dates',
    dateLabel: 'Choisir une date',
    date: 'Date',
    cancelButton: 'Annuler',
    repairHeader: 'Gérer les rapports',
    repairId: 'Numéro du rapport',
    repairStatus: 'Statut du rapport',
    repairStatusOptions: REPAIR_STATUS_LABELS[2].status,
    repairButton: 'Changer de statut',
  },
];
