export const SHOP_ITEM_LABELS = [
  {
    language: 'polish',
    name: 'Nazwa: ',
    brand: 'Marka: ',
    description: 'Opis: ',
    price: 'Cena: ',
    gender: 'Płeć: ',
    color: 'Kolor: ',
    addToCart: 'Dodaj do koszyka',
  },
  {
    language: 'english',
    name: 'Name: ',
    brand: 'Brand: ',
    description: 'Description: ',
    price: 'Price: ',
    gender: 'Gender: ',
    color: 'Color: ',
    addToCart: 'Add to cart',
  },
  {
    language: 'french',
    name: 'Nom: ',
    brand: 'Markque: ',
    description: 'Description: ',
    price: 'Prix: ',
    gender: 'Sexe: ',
    color: 'Couleur: ',
    addToCart: 'Ajoutez en panier',
  },
];
